/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_caotao_ndkexample_TestNDK */

#ifndef _Included_com_example_caotao_ndkexample_TestNDK
#define _Included_com_example_caotao_ndkexample_TestNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_caotao_ndkexample_TestNDK
 * Method:    getNDKString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_caotao_ndkexample_TestNDK_getNDKString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_caotao_ndkexample_TestNDK
 * Method:    convertToInt
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_com_example_caotao_ndkexample_TestNDK_convertToInt__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_example_caotao_ndkexample_TestNDK
 * Method:    convertToInt
 * Signature: (DLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_caotao_ndkexample_TestNDK_convertToInt__DLjava_lang_String_2
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     com_example_caotao_ndkexample_TestNDK
 * Method:    convertToInt
 * Signature: (DLjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_caotao_ndkexample_TestNDK_convertToInt__DLjava_lang_String_2Z
  (JNIEnv *, jobject, jdouble, jstring, jboolean);

/*
 * Class:     com_example_caotao_ndkexample_TestNDK
 * Method:    convertToInt
 * Signature: (DLjava/lang/String;ZLjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_example_caotao_ndkexample_TestNDK_convertToInt__DLjava_lang_String_2ZLjava_lang_Object_2
  (JNIEnv *, jobject, jdouble, jstring, jboolean, jobject);

/*
 * Class:     com_example_caotao_ndkexample_TestNDK
 * Method:    convertToInt
 * Signature: (DLjava/lang/String;ZLcom/example/caotao/ndkexample/TestNDK/InnerClass;)I
 */
JNIEXPORT jint JNICALL Java_com_example_caotao_ndkexample_TestNDK_convertToInt__DLjava_lang_String_2ZLcom_example_caotao_ndkexample_TestNDK_InnerClass_2
  (JNIEnv *, jobject, jdouble, jstring, jboolean, jobject);

/*
 * Class:     com_example_caotao_ndkexample_TestNDK
 * Method:    setNativeCallbacks
 * Signature: (Lcom/example/caotao/ndkexample/NativeCallbacks;)V
 */
JNIEXPORT void JNICALL Java_com_example_caotao_ndkexample_TestNDK_setNativeCallbacks
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
